// <auto-generated />
using EFCore.CodeFirst.DZS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.CodeFirst.Migrations
{
    [DbContext(typeof(AppDBKontext))]
    [Migration("20221011094412_Initiale")]
    partial class Initiale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Arbeiter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Gehalt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Arbeiter");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Manager", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Grad")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Arbeiter", b =>
                {
                    b.OwnsOne("EFCore.CodeFirst.DZS.Personal", "Personal", b1 =>
                        {
                            b1.Property<int>("ArbeiterID")
                                .HasColumnType("int");

                            b1.Property<int>("Alter")
                                .HasColumnType("int");

                            b1.Property<string>("NachName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VorName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ArbeiterID");

                            b1.ToTable("Arbeiter");

                            b1.WithOwner()
                                .HasForeignKey("ArbeiterID");
                        });

                    b.Navigation("Personal")
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Manager", b =>
                {
                    b.OwnsOne("EFCore.CodeFirst.DZS.Personal", "Personal", b1 =>
                        {
                            b1.Property<int>("ManagerID")
                                .HasColumnType("int");

                            b1.Property<int>("Alter")
                                .HasColumnType("int");

                            b1.Property<string>("NachName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VorName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ManagerID");

                            b1.ToTable("Manager");

                            b1.WithOwner()
                                .HasForeignKey("ManagerID");
                        });

                    b.Navigation("Personal")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
