// <auto-generated />
using EFCore.CodeFirst.DZS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.CodeFirst.Migrations
{
    [DbContext(typeof(AppDBKontext))]
    [Migration("20221006100600_Delete_Restrict")]
    partial class Delete_Restrict
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Kategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kategorien");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Lehrer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lehrer");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Produkt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("KategorieID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Strichcode")
                        .HasColumnType("int");

                    b.Property<int>("Vorrat")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KategorieID");

                    b.ToTable("Produkte");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.ProduktEigenschaft", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Breite")
                        .HasColumnType("int");

                    b.Property<string>("Farbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grösse")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProduktEigenschaften");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Alter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("LehrerStudent", b =>
                {
                    b.Property<int>("LehrerID")
                        .HasColumnType("int");

                    b.Property<int>("StudentenID")
                        .HasColumnType("int");

                    b.HasKey("LehrerID", "StudentenID");

                    b.HasIndex("StudentenID");

                    b.ToTable("LehrerStudent");
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Produkt", b =>
                {
                    b.HasOne("EFCore.CodeFirst.DZS.Kategorie", "Kategorie")
                        .WithMany("Produkte")
                        .HasForeignKey("KategorieID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("LehrerStudent", b =>
                {
                    b.HasOne("EFCore.CodeFirst.DZS.Lehrer", null)
                        .WithMany()
                        .HasForeignKey("LehrerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore.CodeFirst.DZS.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.CodeFirst.DZS.Kategorie", b =>
                {
                    b.Navigation("Produkte");
                });
#pragma warning restore 612, 618
        }
    }
}
